# This file was generated by GoReleaser. DO NOT EDIT.
cask "billkit" do
  version "0.2.4"

  on_macos do
    on_arm do
      sha256 "d8d13e6043b65b39fd4be7f8a3a7c17d54391af666d208722d2ce4c1827e5187"
      url "https://github.com/billkit-eu/billkit-cli/releases/download/v#{version}/billkit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f78ec8c74cf0093cac7c601892373ffaca53e32c4d0984506f8497d0e3c0520b"
      url "https://github.com/billkit-eu/billkit-cli/releases/download/v#{version}/billkit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "717eb7d9d5b5c29e0538b8eb404c547c7e48e1749634e31e4becbf3c530f5733"
      url "https://github.com/billkit-eu/billkit-cli/releases/download/v#{version}/billkit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "455db344cd3fe538a0e6b6e9555cea6625eb5dd004604c59a7d1e7a65e0f1168"
      url "https://github.com/billkit-eu/billkit-cli/releases/download/v#{version}/billkit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "billkit"
  desc "The BillKit command-line interface"
  homepage "https://billkit.eu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "billkit"

  # No zap stanza required
end
