# This file was generated by GoReleaser. DO NOT EDIT.
cask "billkit" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "393d63a109ffaf0dc968cac68dae618d2a4ea0083ee87d075159cef4912d3daa"
      url "https://github.com/billkit-eu/billkit-cli/releases/download/v#{version}/billkit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "afcf41647bc07aaa7c0d09b70f35ef038eb00d9d56bcd52ab708fb33c791efc1"
      url "https://github.com/billkit-eu/billkit-cli/releases/download/v#{version}/billkit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "83b03a59a2b001e42e46f1d5400b467569b4349b3542dee78dbf13db34881c54"
      url "https://github.com/billkit-eu/billkit-cli/releases/download/v#{version}/billkit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "65612960e6ca5475167183b438678dfecfbd528deb260cb9c83c50e191bbe9c9"
      url "https://github.com/billkit-eu/billkit-cli/releases/download/v#{version}/billkit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "billkit"
  desc "The BillKit command-line interface"
  homepage "https://billkit.eu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "billkit"

  # No zap stanza required
end
